#title: Shaw Talebi
#logo: /assets/img/headshot_circle.png
#description: text below image
#show_downloads: true
#theme: jekyll-theme-minimal

#title: Cayman theme
description: Nour Khawaled, B.Sc Information Systems.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-cayman
